### PR TITLE
metanorma/metanorma-cli#278 improve LoadError log message

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-cli#278

### Metanorma PR checklist

 - ✗ Breaking changes (list related PRs)
 - ✗ Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - ✗ External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - ✗ Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Can we also display the error message and backtrace, and ask the user to copy/paste the backtrace (after sanitisation of personal information) for the issue?

**Comment by CAMOBAP** [comment]
> Thanks @CAMOBAP ! Can we also display the error message and backtrace, and ask the user to copy/paste the backtrace (after sanitisation of personal information) for the issue?

For this particular the case, a backtrace makes no sense

Maybe we should do this in some global error catch callback with [`at_exit`](https://ruby-doc.org/core/Kernel.html#method-i-at_exit)

I'm not sure if this approach has some negative side effects @ronaldtse @opoudjis maybe you have some insights?

**Comment by opoudjis** [comment]
@CAMOBAP I know that in general in the past metanorma-cli has failed to pass on backtrace, and that has been unhelpful. If a backtrace is available, it needs to be passed on. If anything is going to catch raised errors and print them out, it's going to be metanorma-cli, which is the only executable that matters; if metanorma gem catches errors, it needs to pass them on.

**Comment by ronaldtse** [comment]
> If anything is going to catch raised errors and print them out, it's going to be metanorma-cli, which is the only executable that matters; if metanorma gem catches errors, it needs to pass them on.

Yes. i.e. the user ultimately should be able to trace the thrown error for development tracing.

**Pull request merged**
