### PR TITLE
metanorma/mn-samples-iso#58 pass fonts install manifest file to mn2pdf

### PR DESCRIPTION
**Pull request by CAMOBAP**
Depends on https://github.com/metanorma/isodoc/pull/271

 - metanorma/mn-samples-iso#58

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse this PR contains an issue:

`Fontist::Manifest::Locations.from_hash(@processor.fonts_manifest)` produce manifest without info about font type (Regular, Bold)

```
---
Cambria:
  ! '':
    full_name: Cambria
    paths:
    - "/Applications/Microsoft Excel.app/Contents/Resources/Fonts/Cambria.ttc"
    - "/Applications/Microsoft Excel.app/Contents/Resources/Fonts/Cambriab.ttf"
    - "/Applications/Microsoft Excel.app/Contents/Resources/Fonts/Cambriai.ttf"
    - "/Applications/Microsoft Excel.app/Contents/Resources/Fonts/Cambriaz.ttf"
Cambria Math:
  ! '':
    full_name: Cambria Math
    paths:
    - "/Applications/Microsoft Excel.app/Contents/Resources/Fonts/Cambria.ttc"
Times New Roman:
  ! '':
    full_name: Times New Roman Bold Italic
    paths:
    - "/System/Library/Fonts/Supplemental/Times New Roman Bold Italic.ttf"
    - "/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf"
    - "/System/Library/Fonts/Supplemental/Times New Roman Italic.ttf"
    - "/System/Library/Fonts/Supplemental/Times New Roman.ttf"
Source Han Sans:
  ! '':
    full_name: Source Han Sans Bold
    paths:
    - "/Users/camobap/.fontist/fonts/SourceHanSans-Bold.ttc"
    - "/Users/camobap/.fontist/fonts/SourceHanSans-ExtraLight.ttc"
    - "/Users/camobap/.fontist/fonts/SourceHanSans-Heavy.ttc"
    - "/Users/camobap/.fontist/fonts/SourceHanSans-Light.ttc"
    - "/Users/camobap/.fontist/fonts/SourceHanSans-Medium.ttc"
    - "/Users/camobap/.fontist/fonts/SourceHanSans-Normal.ttc"
    - "/Users/camobap/.fontist/fonts/SourceHanSans-Regular.ttc"
Courier:
  ! '':
    full_name: Courier New
    paths:
    - "/Users/camobap/.fontist/fonts/cour.ttf"
    - "/Users/camobap/.fontist/fonts/courbd.ttf"
    - "/Users/camobap/.fontist/fonts/courbi.ttf"
    - "/Users/camobap/.fontist/fonts/couri.ttf"
Courier New:
  ! '':
    full_name: Courier New Bold Italic
    paths:
    - "/System/Library/Fonts/Supplemental/Courier New Bold Italic.ttf"
    - "/System/Library/Fonts/Supplemental/Courier New Bold.ttf"
    - "/System/Library/Fonts/Supplemental/Courier New Italic.ttf"
    - "/System/Library/Fonts/Supplemental/Courier New.ttf"
    - "/Users/camobap/.fontist/fonts/cour.ttf"
    - "/Users/camobap/.fontist/fonts/courbd.ttf"
    - "/Users/camobap/.fontist/fonts/courbi.ttf"
    - "/Users/camobap/.fontist/fonts/couri.ttf"
```

As a result mn2pdf.jar return error:

```
ERROR: Error in processing font manifest file: java.lang.NullPointerException
Expected format:
Cambria:
  Regular:
    full_name: Cambria
    paths:
    - "~/.fontist/fonts/CAMBRIA.TTC"
  Bold:
    paths:
    - "~/.fontist/fonts/CAMBRIAB.TTF"
Cambria Math:
  Regular:
    paths:
    - "~/.fontist/fonts/CAMBRIA.TTC"
STIX Two Math:
  Regular:
    paths:
    - "~/.fontist/fonts/STIX2Math.otf"
```


@alexeymorozov maybe you can help/suggest what's I'm doing wrong?

**Comment by alexeymorozov** [comment]
Released fontist v1.8.12 with paths grouped by style as in the expected format. Should help.

**Comment by CAMOBAP** [comment]
I can confirm that fix working

**Review by ronaldtse — APPROVED** [review]

**Review by opoudjis — APPROVED** [review]

**Comment by opoudjis** [comment]
> I can confirm that fix working

Reran GHA jobs, still failing

**Comment by ronaldtse** [comment]
@CAMOBAP some test failures like:

```
2021-03-23T00:06:03.9489403Z   1) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection
2021-03-23T00:06:03.9490860Z      Failure/Error: location_manifest = Fontist::Manifest::Locations.from_hash(@processor.fonts_manifest)
2021-03-23T00:06:03.9491777Z 
2021-03-23T00:06:03.9492621Z      Fontist::Errors::FormulaIndexNotFoundError:
2021-03-23T00:06:03.9493719Z        Please fetch `/home/runner/.fontist/formulas/index.yml` index with `fontist update`.
```

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis tests fixed, I propose to fix https://codeclimate.com/github/metanorma/metanorma/pull/171 in separate task (I will create one) if you don't mind

**Comment by ronaldtse** [comment]
Agree, let's merge.

**Pull request merged**
