### PR TITLE
port Shale to Lutaml::Model: https://github.com/metanorma/metanorma/i…

### PR DESCRIPTION
**Pull request by opoudjis**
…ssues/401

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by opoudjis** [comment]
The crashes I'm getting when trying to port this gem from Shale to Lutaml-Model, are:

````
 1) Metanorma::Collection disambiguates destination filenames
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:687:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  2) Metanorma::Collection skips indexing of files in coverpage on request
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:705:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  3) Metanorma::Collection inject repository identifiers
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:725:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  4) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:30:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  5) Metanorma::Collection render html & build doc, pdf, xml files from extracts metadata from collection for Liquid
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:125:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  6) Metanorma::Collection render html & build doc, pdf, xml files from uses presentation XML directive, markup in identifiers
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:223:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  7) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection with documents inline
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:248:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  8) Metanorma::Collection render html & build doc, pdf, xml files from processes section split HTML
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./lib/metanorma/collection/sectionsplit/sectionsplit.rb:41:in `collection_manifest'
     # ./lib/metanorma/collection/sectionsplit/sectionsplit.rb:31:in `build_collection'
     # ./lib/metanorma/compile/compile.rb:211:in `sectionsplit_convert'
     # ./lib/metanorma/compile/compile.rb:156:in `process_ext_simple'
     # ./lib/metanorma/compile/compile.rb:141:in `process_ext'
     # ./lib/metanorma/compile/compile.rb:125:in `block in process_exts_run'
     # ./lib/metanorma/compile/compile.rb:124:in `each'
     # ./lib/metanorma/compile/compile.rb:124:in `process_exts_run'
     # ./lib/metanorma/compile/compile.rb:119:in `process_exts'
     # ./lib/metanorma/compile/compile.rb:35:in `compile'
     # ./spec/collection_complex_spec.rb:298:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  9) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection with multiple documents sectionsplit (source document for links)
     Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
     
     NoMethodError:
       undefined method `parse' for nil
     # ./lib/metanorma/collection/collection.rb:220:in `parse'
     # ./spec/collection_complex_spec.rb:462:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:36:in `chdir'
     # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  10) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection with multiple documents sectionsplit (target document for links)
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_complex_spec.rb:525:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  11) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection with nested YAMLs, directory changes, attachments with absolute paths, attachments with paths outside working directory, implicit identifier for files, svg links outside current file
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_complex_spec.rb:628:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  12) Metanorma::Collection Word collection builds Word collection, no coverpages
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_complex_spec.rb:749:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  13) Metanorma::Collection Word collection builds Word collection, coverpages
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_complex_spec.rb:774:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  14) Metanorma::Collection bilingual document YAML collection
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_complex_spec.rb:799:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  15) Metanorma::Collection parse YAML collection manifest to YAML
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:21:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  16) Metanorma::Collection parse YAML collection to XML
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:129:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  17) Metanorma::Collection parse YAML collection with no document identifiers
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:140:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  18) Metanorma::Collection parse YAML collection with docs inline
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:152:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  19) Metanorma::Collection parse YAML collection with interleaved documents and manifests
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:174:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  20) Metanorma::Collection parse XML collection
      Failure/Error: ::Metanorma::Collection::Config::Config.from_xml(File.read(file))
      
      RuntimeError:
        Attribute 'entry' not found in Metanorma::Collection::Config::Config
      # ./lib/metanorma/collection/collection.rb:216:in `parse'
      # ./spec/collection_spec.rb:402:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  21) Metanorma::Collection parse XML collection with interleaved documents and manifests
      Failure/Error: ::Metanorma::Collection::Config::Config.from_xml(File.read(file))
      
      RuntimeError:
        Attribute 'entry' not found in Metanorma::Collection::Config::Config
      # ./lib/metanorma/collection/collection.rb:216:in `parse'
      # ./spec/collection_spec.rb:411:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  22) Metanorma::Collection parse XML collection with docs inline
      Failure/Error: ::Metanorma::Collection::Config::Config.from_xml(File.read(file))
      
      RuntimeError:
        Attribute 'entry' not found in Metanorma::Collection::Config::Config
      # ./lib/metanorma/collection/collection.rb:216:in `parse'
      # ./spec/collection_spec.rb:420:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  23) Metanorma::Collection parse YAML collection with new format when constructing collection manifest should inherit sectionsplit and have correct format
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:185:in `block (4 levels) in <top (required)>'
      # ./spec/collection_spec.rb:191:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  24) Metanorma::Collection parse YAML collection with new format when constructing collection manifest should allow user to set identifier
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:185:in `block (4 levels) in <top (required)>'
      # ./spec/collection_spec.rb:263:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  25) Metanorma::Collection parse YAML collection with new format when constructing collection manifest should allow user to point fileref to new location conditionally
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:185:in `block (4 levels) in <top (required)>'
      # ./spec/collection_spec.rb:284:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  26) Metanorma::Collection parse YAML collection with new format when parsing and rendering model should allow user to define a proc to run
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:291:in `block (5 levels) in <top (required)>'
      # ./spec/collection_spec.rb:329:in `block (6 levels) in <top (required)>'
      # ./spec/collection_spec.rb:8:in `capture_stdout'
      # ./spec/collection_spec.rb:328:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  27) Metanorma::Collection parse YAML collection with new format when parsing and rendering model should raise error if adoc files not found
      Failure/Error:
        expect { parse_model.render(collection_opts) }.to raise_error(
          Metanorma::AdocFileNotFoundException, /document-1\.adoc not found!/
        )
      
        expected Metanorma::AdocFileNotFoundException with message matching /document-1\.adoc not found!/, got #<NoMethodError: undefined method `parse' for nil> with backtrace:
          # ./lib/metanorma/collection/collection.rb:220:in `parse'
          # ./spec/collection_spec.rb:291:in `block (5 levels) in <top (required)>'
          # ./spec/collection_spec.rb:343:in `block (6 levels) in <top (required)>'
          # ./spec/collection_spec.rb:343:in `block (5 levels) in <top (required)>'
          # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
          # ./spec/spec_helper.rb:36:in `chdir'
          # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
          # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
      # ./spec/collection_spec.rb:343:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  28) Metanorma::Collection parse YAML collection with new format when parsing and rendering model should raise error if YAML files not found
      Failure/Error:
        expect { parse_model.render(collection_opts) }.to raise_error(
          Metanorma::FileNotFoundException,
          /document-1\/collection\.yml not found!/,
        )
      
        expected Metanorma::FileNotFoundException with message matching /document-1\/collection\.yml not found!/, got #<NoMethodError: undefined method `parse' for nil> with backtrace:
          # ./lib/metanorma/collection/collection.rb:220:in `parse'
          # ./spec/collection_spec.rb:291:in `block (5 levels) in <top (required)>'
          # ./spec/collection_spec.rb:357:in `block (6 levels) in <top (required)>'
          # ./spec/collection_spec.rb:357:in `block (5 levels) in <top (required)>'
          # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
          # ./spec/spec_helper.rb:36:in `chdir'
          # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
          # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
      # ./spec/collection_spec.rb:357:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  29) Metanorma::Collection parse YAML collection with new format when parsing and rendering model should compile adoc files and return Metanorma::Collection
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:291:in `block (5 levels) in <top (required)>'
      # ./spec/collection_spec.rb:373:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'

  30) Metanorma::Collection parse YAML collection with new format when parsing and rendering model should render output
      Failure/Error: ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
      
      NoMethodError:
        undefined method `parse' for nil
      # ./lib/metanorma/collection/collection.rb:220:in `parse'
      # ./spec/collection_spec.rb:291:in `block (5 levels) in <top (required)>'
      # ./spec/collection_spec.rb:381:in `block (5 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:36:in `chdir'
      # ./spec/spec_helper.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
````

**Comment by opoudjis** [comment]
@HassanAkbar  Although you performed a bugfix out of this, you did not review this, rerun it, or provide feedback on my usage of lutaml-model. Please do  so in future.

lutaml-model is much stricter about configuration of attributes than Shale was, because it is a reimplementation from scratch. It is not a drop-in equivalent, and it should have been, to minimise impact on other developers. Taking this back to myself to debug.

**Comment by opoudjis** [comment]
No, there is still a bug in lutaml-model.

@HassanAkbar You need to resolve all the issues in lutaml-model, and get this working, by actually running the Metanorma tests. I can't do this iteratively with you.

The issue I am now running into is:

lib/metanorma/collection/config/manifest.rb
````
class Manifest < ::Lutaml::Model::Serializable
...
        attribute :entry, Manifest, collection: true
....

def docref_from_yaml(model, value)
  require "debug"; binding.b
  model.entry = Manifest.from_yaml(value.to_yaml)
end
````

lutaml-model-0.3.8/lib/lutaml/model/serialize.rb

````
define_method(:"from_#{format}") do |data|
  adapter = Lutaml::Model::Config.send(:"#{format}_adapter")
  doc = adapter.parse(data)
  public_send(:"of_#{format}", doc.to_h)
end

data = [{"level"=>"subcollection", "title"=>"Standards", "docref"=>[{"fileref"=>"../collection/dummy.xml", "identifier"=>"ISO 44001", "index"=>true}, {"fileref"=>"dummy.1.xml", "identifier"=>"ISO 44002", "index"=>false}, {"fileref"=>"dummy.xml", "identifier"=>"ISO 44003"}]}]

````

from_yaml is assuming that it will always find a Hash. If the element is a collection, it will be an array.

This is a foundational bug....

**Comment by ronaldtse** [comment]
Thank you @opoudjis @HassanAkbar !

**Pull request merged**
