### PR TITLE
Fix input file calculation logic & raise error if metanorma-pdf.js failed

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-cli/issues/88
 - https://github.com/metanorma/metanorma-cli/issues/89

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 very good idea. Ping me when ready to merge!

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse should tests be updated to the actual results, or code need to be fixed for 

```
rspec ./spec/compile_spec.rb:71 # Metanorma::Compile exports bibdata
rspec ./spec/compile_spec.rb:80 # Metanorma::Compile exports bibdata, rxl
rspec ./spec/compile_spec.rb:99 # Metanorma::Compile exports assets
```

**Comment by ronaldtse** [comment]
Ping @opoudjis to provide direction on the specs.

**Comment by opoudjis** [comment]
> Ping @opoudjis to provide direction on the specs.

Then either @ronaldtse or @CAMOBAP795 should explain to me what is going on. I have a crapload to keep track of in this project, and I've been working on other tasks. What is being asked of me?

**Comment by ronaldtse** [comment]
Should these specs pass or fail?

https://github.com/metanorma/metanorma/pull/65#issuecomment-502234172

If pass, what changes should be made to these specs?

**Comment by opoudjis** [comment]
It's passing my side. And Travis is using obsolete Relaton code: `<bibdata type="standard">` has replaced `<bibdata type="article">`.

Metanorma is clearly using obsolete relaton-* gems on Travis;  it is still using the old gem names!

I've put in the gemspec

`spec.add_development_dependency "metanorma-iso", "~> 1.2`

Travis is `Fetching metanorma-iso 1.1.5 (was 1.1.6)`

... I presume this is because metanorma has not been updated since? Relaunching job.

**Comment by opoudjis** [comment]
https://travis-ci.org/metanorma/metanorma currently passes fine.

I have no idea what is going on here with your earlier posted code branch, but I've said what needs to be said here: the rspec is correct and updated.

**Comment by opoudjis** [comment]
Confirmed that branch works on my environment; merging.

**Comment by ronaldtse** [comment]
Maybe it’s due to Travis gem cache.

**Pull request merged**
