### PR TITLE
Metanorma should no longer require `:type` option when given file is Metanorma XML (WIP)

### PR DESCRIPTION
**Pull request by opoudjis**
See ticket https://github.com/metanorma/metanorma/issues/91  for what this is about.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@abunashir : @opoudjis has switched to finish some other work, and we need your help here since you last touched the dynamic loading of metanorma-* gems.

Could you please help complete this PR for #91?

I believe some code needs to be shifted between `metanorma-cli` and `metanorma` gems. We can always make it work in `metanorma-cli` first by reopening classes from `metanorma` proper.

The goal is to have `metanorma` gem's `class Compile` read in the XML, read the root tag of the XML, and load the appropriate flavor processor. Today, the loading of the flavor processor is in `metanorma-cli`. We need to move that behavior inside `metanorma` gem.

It might be the time to actually solve the dynamic loading problem where the `metanorma` gem is traversing all the Rubygems of a system. Maybe in metanorma-cli we hard-code which gems are available instead of dynamically loading them.

**Comment by abunashir** [comment]
Hey Guys, I'm not sure if I'm missing something here, but I've added a simplified version to detect the the type on #94, let me know if that works. cc: @ronaldtse, @opoudjis

**Comment by opoudjis** [comment]
Your solution presupposes that the root tag will *always* be "{flavour}-standard", and that all we need to do is pull the first part of the tag out, and call that the type.

My solution does not presupposes anything about the root tag of a flavour: instead, it expressly iterates through all registered flavours, records their root tags, and then compares them with the root tag of the XML document. (That's why it needs to migrate to metanorma-cli, as metanorma does not have access to the list of all possible gems.)

I think that we cannot presuppose the root tag structure, especially if metanorma is customised locally. But I may be overengineering this. @ronaldtse which alternative do you want?

**Comment by ronaldtse** [comment]
@abunashir @opoudjis Frankly, I don't like parsing the root tag. There may be a day we use a single root tag, and the flavor gets moved into an element. What we need is a solution that reads the XML and gets an element out of it.

**Comment by opoudjis** [comment]
@abunashir Accordingly, please migrate my code to metanorma-cli as originally requested.

**Comment by abunashir** [comment]
Me neither, but at the same time I'm also concerned about loading each single dependency and then iterate through each of those to figure out the type. It might cause the same slow performance as we had on the earlier version of the cli.

Anyway, if we are okay with performance then I think this pull request should be sufficient, we will only need to adjust the gem loading part there, and since we are using the `.instance` for registry  then once loaded then this pull request should work as expected. @opoudjis: Does this resolve the issue, or any other reason you wanted to migrate these code to the cli?

> @abunashir @opoudjis Frankly, I don't like parsing the root tag. There may be a day we use a single root tag, and the flavor gets moved into an element. What we need is a solution that reads the XML and gets an element out of it.

**Comment by ronaldtse** [comment]
@abunashir @opoudjis this looks good to me. Can we merge this?

**Comment by opoudjis** [comment]
Works because of what you did in metanorma-cli. Thank you @abunashir

**Pull request merged**
