### PR TITLE
Allow Metanorma::Collection to parse collection hash

### PR DESCRIPTION
**Pull request by kwkwan**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Review by opoudjis — CHANGES_REQUESTED** [review]
Will not approve without Rspec test

**Comment by opoudjis** [comment]
... This seems so far to be just a code refactor. Is this ongoing work?

**Comment by kwkwan** [comment]
Yes, it is a code refactor is to expose the parse_model to allow Metanorma::Collection to parse collection in hash, which may be used later.  There is no urgent need to approve this PR as the direction of the code change is still not finalized.

**Comment by kwkwan** [comment]
As this changes will be brought forward to another issue, this PR will be closed.

**Pull request closed without merging**
