### PR TITLE
 put collection artifacts in target place without copy from temp

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/bipm-si-brochure#153

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@opoudjis @abunashir @ronaldtse could you please review this PR, I'm not 100% sure about it

**Comment by opoudjis** [comment]
This is going to be difficult for me to understand, so I'm not going to deal with it immediately (have to do early release, am going on holiday for a week). Could you explain to me the rationale, @CAMOBAP?

**Comment by ronaldtse** [comment]
@opoudjis the old approach creates a file via `Tempfile` and reads it again. However, after writing `Tempfile`, it is possible that the file gets immediately deleted. We ran into this situation when the file processed is large; on GHA, the /tmp directory is immediately cleaned, so the next step of reading the tempfile crashes.

I don't know if this resolves the issue, but it is supposed to be an important bug fix.

**Comment by CAMOBAP** [comment]
ping @opoudjis @abunashir

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Pull request merged**
